//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Basic
{
    public partial class StudentData
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int StudentFees { get; set; }
        public string StudentHomeCity { get; set; }
    }
}
